config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  devise_for :users
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
     resource :favorites, only: [:create, :destroy]
     resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get "search" => "searches#search"
  resources :groups, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    @book_comment = BookComment.new
    @book = Book.find(params[:book_id])
    # if comment.save
    #   # redirect_back(fallback_location: root_path)
    # else
    #   # redirect_back(fallback_location: root_path)
    # end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
    
    @book_comment = BookComment.new
    # redirect_back(fallback_location: root_path)

  end




  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
 <table class="comment">
   <% book.book_comments.each do |book_comment| %>
    <tr>
      <td><%= image_tag book_comment.user.get_profile_image, size: '50x50' %><br>
          <%= book_comment.user.name %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy",book_book_comment_path(book_comment.book,book_comment), method: :delete,remote: true, class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<div class="comment_form">
  <%= form_with model: [book, book_comment], local: false do |f| %>
  <%= f.text_area :comment, rows: '5',class: "form-control" %>
  <div><%= f.submit "送信" %></div>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$("#comment-area").html("<%= j(render 'book_comments/comment', book: @book,book_comment: @book_comment) %>")

app/views/book_comments/destroy.js.erb
$("#comment-area").html("<%= j(render 'book_comments/comment', book: @book,book_comment: @book_comment) %>")